// data.ts

export const userData = [
    {
      id: 1,
      isChecked: false,
      name: "John Doe",
      number: "+2547456789",
      email: "john.doe@example.com",
      balance: "Ksh 12450",
      status: "Active",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 2,
      isChecked: false,
      name: "Jane Smith",
      number: "+2547456789",
      email: "jane.smith@example.com",
      balance: "Ksh 450",
      status: "Suspended",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 3,
      isChecked: false,
      name: "Alice Brown",
      number: "+254712345678",
      email: "alice.brown@example.com",
      balance: "Ksh 2340",
      status: "Active",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 4,
      isChecked: false,
      name: "Bob Johnson",
      number: "+254734567890",
      email: "bob.johnson@example.com",
      balance: "Ksh 8400",
      status: "Suspended",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 5,
      isChecked: false,
      name: "Chris Evans",
      number: "+254701234567",
      email: "chris.evans@example.com",
      balance: "Ksh 960",
      status: "Active",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 6,
      isChecked: false,
      name: "Diana Prince",
      number: "+254746789012",
      email: "diana.prince@example.com",
      balance: "Ksh 1450",
      status: "Suspended",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 7,
      isChecked: false,
      name: "Edward King",
      number: "+254715678901",
      email: "edward.king@example.com",
      balance: "Ksh 2300",
      status: "Active",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 8,
      isChecked: false,
      name: "Fiona Green",
      number: "+254789012345",
      email: "fiona.green@example.com",
      balance: "Ksh 10450",
      status: "Active",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 9,
      isChecked: false,
      name: "George White",
      number: "+254732145678",
      email: "george.white@example.com",
      balance: "Ksh 780",
      status: "Suspended",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
    {
      id: 10,
      isChecked: false,
      name: "Hannah Black",
      number: "+254790123456",
      email: "hannah.black@example.com",
      balance: "Ksh 13450",
      status: "Active",
      manage: [
        { src: "/edit.svg", alt: "Edit" },
        { src: "/dot3.svg", alt: "More Options" },
      ],
    },
  ];

  export const recent = [
    {
      id: 1,
      name: "Grace Mwai",
      balance: "Ksh 450",
      transactions: 5,
      applaunches: 10,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 2,
      name: "John Doe",
      balance: "Ksh 1200",
      transactions: 3,
      applaunches: 7,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 3,
      name: "Jane Smith",
      balance: "Ksh 850",
      transactions: 8,
      applaunches: 15,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 4,
      name: "Peter Mwangi",
      balance: "Ksh 300",
      transactions: 2,
      applaunches: 4,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 5,
      name: "Alice Njuguna",
      balance: "Ksh 600",
      transactions: 6,
      applaunches: 12,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 6,
      name: "Michael Otieno",
      balance: "Ksh 750",
      transactions: 4,
      applaunches: 9,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 7,
      name: "Cynthia Wanjiru",
      balance: "Ksh 500",
      transactions: 7,
      applaunches: 14,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 8,
      name: "Samuel Kariuki",
      balance: "Ksh 1050",
      transactions: 5,
      applaunches: 8,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 9,
      name: "Diana Kilonzo",
      balance: "Ksh 950",
      transactions: 6,
      applaunches: 11,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 10,
      name: "Tom Njoroge",
      balance: "Ksh 400",
      transactions: 72,
      applaunches: 105,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
];
