// data.ts

export const userData = [
  {
    id: 1,
    isChecked: false,
    name: "John Mwangi",
    number: "+2547456789",
    email: "john.mwangi@gmail.com",
    balance: "Ksh 12450",
    status: "Active",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 2,
    isChecked: false,
    name: "Jane Wambui",
    number: "+2547456789",
    email: "jane.wambui@yahoo.com",
    balance: "Ksh 450",
    status: "Suspended",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 3,
    isChecked: false,
    name: "Alice Njeri",
    number: "+254712345678",
    email: "alice.njeri@gmail.com",
    balance: "Ksh 2340",
    status: "Active",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 4,
    isChecked: false,
    name: "Bob Otieno",
    number: "+254734567890",
    email: "bob.otieno@yahoo.com",
    balance: "Ksh 8400",
    status: "Suspended",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 5,
    isChecked: false,
    name: "Chris Chege",
    number: "+254701234567",
    email: "chris.chege@gmail.com",
    balance: "Ksh 960",
    status: "Active",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 6,
    isChecked: false,
    name: "Diana Achieng",
    number: "+254746789012",
    email: "diana.achieng@yahoo.com",
    balance: "Ksh 1450",
    status: "Suspended",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 7,
    isChecked: false,
    name: "Edward Kamau",
    number: "+254715678901",
    email: "edward.kamau@gmail.com",
    balance: "Ksh 2300",
    status: "Active",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 8,
    isChecked: false,
    name: "Fiona Wangechi",
    number: "+254789012345",
    email: "fiona.wangechi@yahoo.com",
    balance: "Ksh 10450",
    status: "Active",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 9,
    isChecked: false,
    name: "George Odhiambo",
    number: "+254732145678",
    email: "george.odhiambo@gmail.com",
    balance: "Ksh 780",
    status: "Suspended",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
  {
    id: 10,
    isChecked: false,
    name: "Hannah Nyambura",
    number: "+254790123456",
    email: "hannah.nyambura@yahoo.com",
    balance: "Ksh 13450",
    status: "Active",
    manage: [
      { src: "/edit.svg", alt: "Edit" },
      { src: "/dot3.svg", alt: "More Options" },
    ],
  },
];


  export const recent = [
    {
      id: 1,
      name: "Grace Mwai",
      balance: "Ksh 450",
      transactions: 5,
      applaunches: 10,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 2,
      name: "John Doe",
      balance: "Ksh 1200",
      transactions: 3,
      applaunches: 7,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 3,
      name: "Jane Smith",
      balance: "Ksh 850",
      transactions: 8,
      applaunches: 15,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 4,
      name: "Peter Mwangi",
      balance: "Ksh 300",
      transactions: 2,
      applaunches: 4,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 5,
      name: "Alice Njuguna",
      balance: "Ksh 600",
      transactions: 6,
      applaunches: 12,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 6,
      name: "Michael Otieno",
      balance: "Ksh 750",
      transactions: 4,
      applaunches: 9,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 7,
      name: "Cynthia Wanjiru",
      balance: "Ksh 500",
      transactions: 7,
      applaunches: 14,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 8,
      name: "Samuel Kariuki",
      balance: "Ksh 1050",
      transactions: 5,
      applaunches: 8,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 9,
      name: "Diana Kilonzo",
      balance: "Ksh 950",
      transactions: 6,
      applaunches: 11,
      status: "Active",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
    {
      id: 10,
      name: "Tom Njoroge",
      balance: "Ksh 400",
      transactions: 72,
      applaunches: 105,
      status: "Suspended",
      manage1: "/edit.svg",
      manage2: "/dot3.svg",
    },
];

export const userActivities = [
  {
    userId: 1,
    activities: [
      { action: "Created a HabaPay account", time: "Today.01:07PM" },
      { action: "Withdrew Ksh 240", time: "Yesterday.11:30AM" },
      { action: "Made a payment of Ksh 500", time: "2 days ago.03:45PM" },
      { action: "Linked a new bank account", time: "2 days ago.09:00AM" },
      { action: "Received Ksh 1000", time: "3 days ago.02:30PM" },
    ],
  },
  {
    userId: 2,
    activities: [
      { action: "Deposited Ksh 300", time: "Yesterday.10:15AM" },
      { action: "Withdrew Ksh 150", time: "3 days ago.05:30PM" },
      { action: "Made a payment of Ksh 250", time: "4 days ago.09:45AM" },
      { action: "Linked a new phone number", time: "5 days ago.03:10PM" },
    ],
  },
  {
    userId: 3,
    activities: [
      { action: "Transferred Ksh 1000", time: "Today.09:30AM" },
      { action: "Made a payment of Ksh 1500", time: "Yesterday.03:00PM" },
      { action: "Deposited Ksh 700", time: "3 days ago.12:00PM" },
      { action: "Withdrew Ksh 100", time: "4 days ago.06:15PM" },
      { action: "Received Ksh 2000", time: "5 days ago.02:30PM" },
    ],
  },
  {
    userId: 4,
    activities: [
      { action: "Added Ksh 500", time: "Today.12:00PM" },
      { action: "Withdrew Ksh 200", time: "Yesterday.02:15PM" },
      { action: "Made a payment of Ksh 400", time: "2 days ago.08:45AM" },
      { action: "Linked a new bank account", time: "3 days ago.04:20PM" },
      { action: "Received Ksh 1200", time: "4 days ago.01:30PM" },
    ],
  },
  {
    userId: 5,
    activities: [
      { action: "Transferred Ksh 500", time: "Today.10:00AM" },
      { action: "Deposited Ksh 150", time: "Yesterday.01:45PM" },
      { action: "Made a payment of Ksh 600", time: "2 days ago.09:15AM" },
      { action: "Linked a new phone number", time: "3 days ago.02:00PM" },
    ],
  },
  {
    userId: 6,
    activities: [
      { action: "Withdrew Ksh 200", time: "Today.11:30AM" },
      { action: "Deposited Ksh 500", time: "Yesterday.04:15PM" },
      { action: "Made a payment of Ksh 800", time: "2 days ago.10:00AM" },
      { action: "Transferred Ksh 400", time: "3 days ago.06:30PM" },
    ],
  },
  {
    userId: 7,
    activities: [
      { action: "Transferred Ksh 100", time: "Today.01:00PM" },
      { action: "Received Ksh 600", time: "Yesterday.05:00PM" },
      { action: "Withdrew Ksh 300", time: "2 days ago.09:30AM" },
      { action: "Deposited Ksh 250", time: "3 days ago.11:15AM" },
    ],
  },
  {
    userId: 8,
    activities: [
      { action: "Deposited Ksh 500", time: "Today.02:00PM" },
      { action: "Withdrew Ksh 150", time: "Yesterday.03:30PM" },
      { action: "Made a payment of Ksh 350", time: "2 days ago.08:00AM" },
      { action: "Linked a new phone number", time: "3 days ago.12:00PM" },
      { action: "Received Ksh 5000", time: "4 days ago.10:00AM" },
    ],
  },
  {
    userId: 9,
    activities: [
      { action: "Transferred Ksh 1000", time: "Today.03:00PM" },
      { action: "Made a payment of Ksh 200", time: "Yesterday.04:45PM" },
      { action: "Withdrew Ksh 500", time: "2 days ago.01:00PM" },
      { action: "Deposited Ksh 700", time: "3 days ago.05:30PM" },
    ],
  },
  {
    userId: 10,
    activities: [
      { action: "Made a payment of Ksh 300", time: "Today.10:45AM" },
      { action: "Withdrew Ksh 100", time: "Yesterday.12:00PM" },
      { action: "Transferred Ksh 600", time: "2 days ago.09:30AM" },
      { action: "Deposited Ksh 200", time: "3 days ago.11:00AM" },
      { action: "Received Ksh 1500", time: "4 days ago.02:00PM" },
    ],
  },
];

export const users = [
  { userId: 1, userName: "James Nakamoto" },
  { userId: 2, userName: "Alice Johnson" },
  { userId: 3, userName: "John Doe" },
  { userId: 4, userName: "Maria Lopez" },
  { userId: 5, userName: "Michael Smith" },
  { userId: 6, userName: "Sara Connor" },
  { userId: 7, userName: "David Brown" },
  { userId: 8, userName: "Sophia Wilson" },
  { userId: 9, userName: "Daniel Lee" },
  { userId: 10, userName: "Rachel Adams" },
];

